name: kinetic_qr
description: "A Flutter project for scanning and generating QR codes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add your assets here:
  # assets:
  #   - images/example_image.png

  # Add custom fonts here if needed:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
